apiVersion: v1
kind: Pod
metadata:
  name: staging-php-pesbuk
  namespace: staging
  labels:
    app: facebook
spec:
  volumes:
    - name: staging-config-fb
      configMap:
        name: stag-fb-configmap-sp3

  containers:
  - name: sosial-media
    image: benja123/sp3-sosmed:1.0
    ports:
    - containerPort: 8081
    volumeMounts:
    - name: staging-config-fb
      mountPath: "/var/www/html/config.php"
      subPath: "config.php"
